# Generated by Django 6.0 on 2025-12-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.CharField(db_index=True, help_text='IMDb ID (nconst)', max_length=12, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, help_text='TMDB ID актёра', null=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='ActorProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_professions', to='sixmovies.actor')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_actors', to='sixmovies.profession')),
            ],
            options={
                'db_table': 'actor_professions',
                'unique_together': {('actor', 'profession')},
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='professions',
            field=models.ManyToManyField(related_name='actors', through='sixmovies.ActorProfession', to='sixmovies.profession'),
        ),
    ]
