# Generated by Django 6.0 on 2025-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tconst', models.CharField(db_index=True, help_text="IMDb ID, например 'tt0468569'", max_length=12, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, help_text='TMDB ID фильма/сериала', null=True)),
                ('title_type', models.CharField(db_index=True, help_text='movie, tvSeries, tvMovie, short, tvEpisode, etc.', max_length=32)),
                ('primary_title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=512)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='sixmovies.genre')),
            ],
            options={
                'db_table': 'titles',
                'indexes': [models.Index(fields=['title_type'], name='titles_title_t_5920f2_idx'), models.Index(fields=['start_year'], name='titles_start_y_addcd8_idx')],
            },
        ),
    ]
