# Generated by Django 6.0 on 2025-12-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0002_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='known_for',
            field=models.ManyToManyField(blank=True, related_name='featured_actors', to='sixmovies.title'),
        ),
    ]
