# Generated by Django 6.0 on 2025-12-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0003_actor_known_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlePrincipal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordering', models.IntegerField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('job', models.CharField(blank=True, max_length=256, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_roles', to='sixmovies.actor')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='sixmovies.title')),
            ],
            options={
                'db_table': 'titles_principals',
            },
        ),
        migrations.CreateModel(
            name='TitlePrincipalCharacter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(db_index=True, max_length=512)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='sixmovies.titleprincipal')),
            ],
            options={
                'db_table': 'titles_principal_characters',
            },
        ),
        migrations.AddIndex(
            model_name='titleprincipal',
            index=models.Index(fields=['category'], name='titles_prin_categor_83649e_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipal',
            index=models.Index(fields=['ordering'], name='titles_prin_orderin_e03359_idx'),
        ),
        migrations.AddIndex(
            model_name='titleprincipalcharacter',
            index=models.Index(fields=['character_name'], name='titles_prin_charact_e5ed0c_idx'),
        ),
    ]
