# Generated by Django 6.0 on 2025-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0004_titleprincipal_titleprincipalcharacter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='imdb_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
