# Generated by Django 6.0 on 2025-12-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0005_title_imdb_rating_title_imdb_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight_role', models.FloatField(help_text='w1 — вес компоненты S(role)')),
                ('weight_quality', models.FloatField(help_text='w2 — вес компоненты S(quality)')),
                ('weight_reach', models.FloatField(help_text='w3 — вес компоненты S(reach)')),
                ('global_mean_rating', models.FloatField(help_text='C — средний IMDb рейтинг по базе')),
                ('min_votes_for_weight', models.IntegerField(help_text='M — минимальное число голосов для сглаживания рейтинга')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'popularity_versions',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='popularity_score',
            field=models.FloatField(blank=True, db_index=True, help_text='Агрегированный рейтинг популярности актёра', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='popularity_version',
            field=models.ForeignKey(blank=True, help_text='Ссылка на версию расчёта популярности', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='sixmovies.popularityversion'),
        ),
    ]
