# Generated by Django 6.0 on 2025-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0006_popularityversion_actor_popularity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='is_voice_actor',
            field=models.BooleanField(default=False),
        ),
    ]
