# Generated by Django 6.0 on 2025-12-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0007_actor_is_voice_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, help_text='Количество общих тайтлов (clamped ≤ 3 в алгоритме SCS)')),
                ('actor_id_high', models.ForeignKey(db_column='actor_id_high', on_delete=django.db.models.deletion.CASCADE, related_name='edges_high', to='sixmovies.actor')),
                ('actor_id_low', models.ForeignKey(db_column='actor_id_low', on_delete=django.db.models.deletion.CASCADE, related_name='edges_low', to='sixmovies.actor')),
            ],
            options={
                'db_table': 'actor_edges',
                'indexes': [models.Index(fields=['actor_id_low'], name='actor_edges_actor_i_513e37_idx'), models.Index(fields=['actor_id_high'], name='actor_edges_actor_i_1ad882_idx')],
                'unique_together': {('actor_id_low', 'actor_id_high')},
            },
        ),
    ]
