# Generated by Django 6.0 on 2025-12-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0008_actoredge'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='blackmark',
            field=models.BooleanField(default=False),
        ),
    ]
