# Generated by Django 6.0 on 2025-12-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmovies', '0009_actor_blackmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='wildcard',
            field=models.BooleanField(default=False),
        ),
    ]
